[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-l>e'
  let g:user_emmet_settings = webapi#json#decode(join(readfile(expand('~/.vim/snippet/snippets_reactnative.json')), "\n"))
'''
on_ft = ['html','css','javascript','typescript']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescriptreact','typescript']

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_add = '''
  let g:previm_open_cmd = "open -a safari"
  nmap <Leader>pre :PrevimOpen<CR>
'''

[[plugins]]
repo = 'prettier/vim-prettier'
hook_add = '''
  let g:prettier#config#tab_width = 2
  let g:prettier#config#jsx_bracket_same_line = 'true'
  let g:prettier#config#bracket_spacing = 'true'
'''
#let g:prettier#config#print_width = 100
#let g:prettier#config#single_quote = 'true'
#let g:prettier#config#trailing_comma = 'es5'
on_ft = ['javascript','typescript']

# [[plugins]]
# repo = 'Shougo/neocomplcache'

# [[plugins]]
# repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
# hook_add = '''
#   inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
#   inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
#   inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
