[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'


[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  set laststatus=2
  let g:airline_theme = 'gruvbox'
  let g:airline#extensions#branch#enabled = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#wordcount#enabled = 0
  let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'y', 'z']]
  let g:airline_section_c = '%t'
  let g:airline_section_x = '%{&filetype}'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nmap <Leader>n :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_enabled = 0
  let g:gitgutter_map_keys = 0
  nmap <Leader>gg :GitGutterToggle<CR>
  nmap <Leader>gn <Plug>(GitGutterNextHunk)
  nmap <Leader>gp <Plug>(GitGutterPrevHunk)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
  let g:NERDCreateDefaultMappings = 0
  let g:NERDSpaceDelims = 1
  nmap <Leader>/ <Plug>NERDCommenterToggle
'''


[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  nmap <Leader>ig :IndentGuidesToggle<CR>
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <Leader>e <Plug>(easymotion-prefix)
  let g:EasyMotion_smartcase = 1
  let g:EasyMotion_keys = 'ASDFGHJKL;'
  let g:EasyMotion_use_upper = 1
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
  nmap <Leader>ee <Plug>(easymotion-s2)
  xmap <Leader>ee <Plug>(easymotion-s2)
  nmap <Leader>ej <Plug>(easymotion-j)
  nmap <Leader>ek <Plug>(easymotion-k)
  nmap <Leader>e/ <Plug>(easymotion-sn)
  xmap <Leader>e/ <Plug>(easymotion-sn)
  omap <Leader>e/ <Plug>(easymotion-tn)
  nmap <Leader>eL <Plug>(easymotion-overwin-line)
  hi EasyMotionTarget guifg=#80a0ff ctermfg=81
'''

[[plugins]]
repo = 'justinmk/vim-sneak'
hook_add = '''
  nmap <Leader>s <Plug>Sneak_s
  nmap <Leader>S <Plug>Sneak_S
'''

[[plugins]]
repo = 'vim-scripts/ReplaceWithRegister'
hook_add = '''
  nmap <Leader>r  <Plug>ReplaceWithRegisterOperator
  nmap <Leader>rr <Plug>ReplaceWithRegisterLine
  xmap <Leader>r  <Plug>ReplaceWithRegisterVisual
'''

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
  let g:camelcasemotion_key = '<Leader>w'
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <Leader>t :<C-u>TagbarToggle<CR>
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  let g:ctrlp_map = '<Leader><C-p>'
'''

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
hook_add = '''
  nmap <Leader>ms :1ShowMarksOnce<CR>
  nmap <Leader>mp :1PreviewMarks<CR>
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  let g:lsp_diagnostics_float_cursor = 0
  let g:lsp_diagnostics_echo_cursor= 1
  let g:lsp_virtual_text_enabled = 0
  nmap <Leader>ld :LspDefinition<CR>
  nmap <Leader>lD :LspPeekDefinition<CR>
  nmap <Leader>li :LspImplementation<CR>
  nmap <Leader>lI :LspPeekImplementation<CR>
  nmap <Leader>lc :LspDeclaration<CR>
  nmap <Leader>lC :LspPeekDeclaration<CR>

  nmap <Leader>lt :LspTypeDefinition<CR>
  nmap <Leader>lT :LspPeekTypeDefinition<CR>

  nmap <Leader>ll :LspDocumentDiagnostics<CR>
  nmap <Leader>lf :LspDocumentFormat<CR>
  nmap <Leader>ls :LspWorkspaceSymbol<CR>
  nmap <Leader>lS :LspDocumentSymbol<CR>
  nmap <Leader>lh :LspHover<CR>
  nmap <Leader>lH :LspReferences<CR>

  nmap <Leader>ln :LspNextDiagnostic<CR>
  nmap <Leader>lN :LspPreviousDiagnostic<CR>
  nmap <Leader>le :LspNextError<CR>
  nmap <Leader>lE :LspPreviousError<CR>
  nmap <Leader>lr :LspNextReference<CR>
  nmap <Leader>lR :LspPreviousRefarence<CR>
  nmap <Leader>lw :LspNextWarning<CR>
  nmap <Leader>lW :LspPreviousWarning<CR>
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

# [[plugins]]
# repo = 'AndrewRadev/splitjoin.vim'
# [[plugins]]
# repo = 'tpope/vim-surround'

